import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#0b0f14' },
  headerSafe: { backgroundColor: '#0b0f14' },
  header: {
    paddingTop: Platform.select({ ios: 12, android: 8 }),
    paddingHorizontal: 16,
    paddingBottom: 12,
    backgroundColor: '#0b0f14',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  adminPanel: {
    position: 'absolute',
    top: 80,
    left: 16,
    right: 16,
    bottom: 16,
    backgroundColor: '#111827',
    borderRadius: 16,
    padding: 16,
    zIndex: 10,
  },
  adminTitle: {
    color: 'white',
    fontWeight: '700',
    fontSize: 18,
    marginBottom: 12,
  },
  adminTabBar: {
    flexDirection: 'row',
    marginBottom: 12,
    backgroundColor: '#1f2937',
    borderRadius: 10,
    padding: 4,
  },
  adminTabBtn: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 8,
    alignItems: 'center',
  },
  adminTabBtnActive: {
    backgroundColor: '#2563eb',
  },
  adminTabText: {
    color: '#94a3b8',
    fontWeight: '600',
  },
  adminTabTextActive: {
    color: 'white',
    fontWeight: '700',
  },
  brand: { color: 'white', fontSize: 20, fontWeight: '700' },
  headerActions: { flexDirection: 'row', gap: 8 },
  linkBtn: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 8,
    backgroundColor: '#1a2230',
  },
  linkText: { color: '#cbd5e1', fontWeight: '600' },
  primaryBtn: { backgroundColor: '#2563eb' },
  primaryText: { color: 'white' },
  searchRow: {
    flexDirection: 'row',
    padding: 16,
    backgroundColor: '#0b0f14',
  },
  searchInput: {
    flex: 1,
    backgroundColor: '#111827',
    color: 'white',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  searchBtn: {
    backgroundColor: '#2563eb',
    paddingHorizontal: 14,
    borderRadius: 12,
    justifyContent: 'center',
    marginLeft: 8,
  },
  searchBtnText: { color: 'white', fontWeight: '700' },
  tabBarWrapper: {
    paddingHorizontal: 16,
    paddingTop: 12,
    backgroundColor: '#0b0f14',
  },
  tabBar: {
    flexDirection: 'row',
    backgroundColor: '#111827',
    borderRadius: 12,
    padding: 4,
  },
  tabButton: {
    flex: 1,
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  tabButtonActive: {
    backgroundColor: '#2563eb',
  },
  tabButtonText: {
    color: '#94a3b8',
    fontWeight: '600',
  },
  tabButtonTextActive: {
    color: 'white',
    fontWeight: '700',
  },
  createScroll: { flex: 1, backgroundColor: '#0b0f14' },
  createScrollContent: { paddingBottom: 32 },
  list: { padding: 16 },
  card: {
    backgroundColor: '#0f172a',
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#1f2937',
  },
  cardRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  cardContent: {
    flex: 1,
  },
  cardHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  cardImageContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 8,
  },
  cardTitle: {
    color: 'white',
    fontSize: 16,
    fontWeight: '700',
    flex: 1,
    marginRight: 8,
  },
  cardPrice: { color: '#86efac', fontWeight: '800' },
  cardMeta: { color: '#94a3b8', marginTop: 4 },
  cardDesc: { color: '#cbd5e1', marginTop: 6 },
  pillRow: { flexDirection: 'row', marginTop: 10 },
  pill: {
    color: '#cbd5e1',
    backgroundColor: '#1f2937',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 999,
    marginRight: 8,
  },
  centerRow: { paddingHorizontal: 16, paddingVertical: 8 },
  error: { color: '#fda4af' },
  createBox: {
    marginHorizontal: 16,
    marginBottom: 12,
    padding: 16,
    backgroundColor: '#111827',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#1f2937',
  },
  createTitle: {
    color: 'white',
    fontWeight: '700',
    fontSize: 16,
    marginBottom: 8,
  },
  createInput: {
    backgroundColor: '#0f172a',
    color: 'white',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 8,
  },
  unitRow: { flexDirection: 'row', marginBottom: 8 },
  unitChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: '#0f172a',
    borderWidth: 1,
    borderColor: '#1f2937',
    marginRight: 8,
  },
  unitChipActive: { backgroundColor: '#2563eb', borderColor: '#2563eb' },
  unitChipText: { color: '#cbd5e1', fontWeight: '600', letterSpacing: 0.5 },
  unitChipTextActive: { color: 'white' },
  createTextarea: { minHeight: 80, textAlignVertical: 'top' },
  createBtn: {
    backgroundColor: '#2563eb',
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
  },
  createBtnText: { color: 'white', fontWeight: '700', fontSize: 15 },
  createError: { color: '#fda4af', fontSize: 13, marginTop: 4 },
  createSuccess: { color: '#bbf7d0', fontSize: 13, marginTop: 4 },
  guestNotice: {
    top: 16,
    marginHorizontal: 16,
    marginBottom: 12,
    padding: 20,
    backgroundColor: '#111827',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#1f2937',
  },
  guestNoticeTitle: {
    color: 'white',
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 4,
  },
  guestNoticeText: {
    color: '#cbd5e1',
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 12,
  },
  guestActions: { flexDirection: 'row', gap: 12 },
  secondaryBtn: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#1f2937',
    backgroundColor: '#0f172a',
  },
  secondaryBtnText: { color: '#cbd5e1', fontWeight: '600' },
  secondaryBtnPrimary: { backgroundColor: '#2563eb', borderColor: '#2563eb' },
  secondaryBtnPrimaryText: { color: 'white', fontWeight: '700' },
});
