import { StyleSheet, Platform } from 'react-native';
import { Colors } from './theme/colors';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: Colors.background },
  headerSafe: { backgroundColor: Colors.background },
  header: {
    paddingTop: Platform.select({ ios: 12, android: 8 }),
    paddingHorizontal: 16,
    paddingBottom: 12,
    backgroundColor: Colors.background,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  adminPanel: {
    position: 'absolute',
    top: 80,
    left: 16,
    right: 16,
    bottom: 16,
    backgroundColor: Colors.surface,
    borderRadius: 16,
    padding: 16,
    zIndex: 10,
  },
  adminTitle: {
    color: Colors.text,
    fontWeight: '700',
    fontSize: 18,
    marginBottom: 12,
  },
  adminTabBar: {
    flexDirection: 'row',
    marginBottom: 12,
    backgroundColor: Colors.surfaceAlt,
    borderRadius: 10,
    padding: 4,
  },
  adminTabBtn: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 8,
    alignItems: 'center',
  },
  adminTabBtnActive: {
    backgroundColor: Colors.primary,
  },
  adminTabText: {
    color: Colors.textMuted,
    fontWeight: '600',
  },
  adminTabTextActive: {
    color: Colors.text,
    fontWeight: '700',
  },
  brand: { color: Colors.text, fontSize: 20, fontWeight: '700' },
  headerActions: { flexDirection: 'row', gap: 8 },
  linkBtn: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 8,
    backgroundColor: Colors.surfaceAlt,
  },
  linkText: { color: Colors.textSubtle, fontWeight: '600' },
  primaryBtn: { backgroundColor: Colors.primary },
  primaryText: { color: Colors.text },
  searchRow: {
    flexDirection: 'row',
    padding: 16,
    backgroundColor: Colors.background,
  },
  searchInput: {
    flex: 1,
    backgroundColor: Colors.surface,
    color: Colors.text,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  searchBtn: {
    backgroundColor: Colors.primary,
    paddingHorizontal: 14,
    borderRadius: 12,
    justifyContent: 'center',
    marginLeft: 8,
  },
  searchBtnText: { color: Colors.text, fontWeight: '700' },
  tabBarWrapper: {
    paddingHorizontal: 16,
    paddingTop: 12,
    backgroundColor: Colors.background,
  },
  tabBar: {
    flexDirection: 'row',
    backgroundColor: Colors.surface,
    borderRadius: 12,
    padding: 4,
  },
  tabButton: {
    flex: 1,
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  tabButtonActive: {
    backgroundColor: Colors.primary,
  },
  tabButtonText: {
    color: Colors.textMuted,
    fontWeight: '600',
  },
  tabButtonTextActive: {
    color: Colors.text,
    fontWeight: '700',
  },
  createScroll: { flex: 1, backgroundColor: Colors.background },
  createScrollContent: { paddingBottom: 32 },
  list: { padding: 16 },
  card: {
    backgroundColor: Colors.surfaceMuted,
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  cardRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  cardContent: {
    flex: 1,
  },
  cardHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  cardImageContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 8,
  },
  cardTitle: {
    color: Colors.text,
    fontSize: 16,
    fontWeight: '700',
    flex: 1,
    marginRight: 8,
  },
  cardPrice: { color: Colors.success, fontWeight: '800' },
  cardMeta: { color: Colors.textMuted, marginTop: 4 },
  cardDesc: { color: Colors.textSubtle, marginTop: 6 },
  pillRow: { flexDirection: 'row', marginTop: 10 },
  pill: {
    color: Colors.textSubtle,
    backgroundColor: Colors.surfaceAlt,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 999,
    marginRight: 8,
  },
  centerRow: { paddingHorizontal: 16, paddingVertical: 8 },
  error: { color: Colors.error },
  createBox: {
    marginHorizontal: 16,
    marginBottom: 12,
    padding: 16,
    backgroundColor: Colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  createTitle: {
    color: Colors.text,
    fontWeight: '700',
    fontSize: 16,
    marginBottom: 8,
  },
  createInput: {
    backgroundColor: Colors.surfaceMuted,
    color: Colors.text,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 8,
  },
  unitRow: { flexDirection: 'row', marginBottom: 8 },
  unitChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: Colors.surfaceMuted,
    borderWidth: 1,
    borderColor: Colors.border,
    marginRight: 8,
  },
  unitChipActive: { backgroundColor: Colors.primary, borderColor: Colors.primary },
  unitChipText: { color: Colors.textSubtle, fontWeight: '600', letterSpacing: 0.5 },
  unitChipTextActive: { color: Colors.text },
  createTextarea: { minHeight: 80, textAlignVertical: 'top' },
  createBtn: {
    backgroundColor: Colors.primary,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
  },
  createBtnText: { color: Colors.text, fontWeight: '700', fontSize: 15 },
  createError: { color: Colors.error, fontSize: 13, marginTop: 4 },
  createSuccess: { color: Colors.successMuted, fontSize: 13, marginTop: 4 },
  guestNotice: {
    top: 16,
    marginHorizontal: 16,
    marginBottom: 12,
    padding: 20,
    backgroundColor: Colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  guestNoticeTitle: {
    color: Colors.text,
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 4,
  },
  guestNoticeText: {
    color: Colors.textSubtle,
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 12,
  },
  guestActions: { flexDirection: 'row', gap: 12 },
  secondaryBtn: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.surfaceMuted,
  },
  secondaryBtnText: { color: Colors.textSubtle, fontWeight: '600' },
  secondaryBtnPrimary: { backgroundColor: Colors.primary, borderColor: Colors.primary },
  secondaryBtnPrimaryText: { color: Colors.text, fontWeight: '700' },

  // ProfileMenu styles
  profileMenuBackdrop: {
    flex: 1,
    backgroundColor: Colors.overlay,
    justifyContent: 'flex-start',
    paddingTop: 60,
  },
  profileMenuSheet: {
    marginHorizontal: 16,
    backgroundColor: Colors.surface,
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: Colors.border,
    // Elevation/shadow for separation
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 16,
    elevation: 12,
  },
  profileMenuHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  profileMenuAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    marginRight: 12,
    backgroundColor: Colors.surfaceAlt,
  },
  profileMenuAvatarFallback: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileMenuAvatarText: { color: Colors.text, fontWeight: '700', fontSize: 18 },
  profileMenuName: { color: Colors.text, fontSize: 16, fontWeight: '700' },
  profileMenuEmail: { color: Colors.textMuted, fontSize: 12 },
  profileMenuItem: {
    paddingVertical: 10,
  },
  profileMenuItemText: { color: Colors.text, fontSize: 14 },
  profileMenuSeparator: { height: 1, backgroundColor: Colors.border, marginVertical: 8 },
});
